### ISSUE TITLE
libpjsua2.so: x86 has text relocations, is has been fix but i got new error when i build openssl with option -no-asm

### ISSUE THREAD

**Issue by omar-othmann** [VoiSmart/pjsip-android-builder#29]
Hi. i have error with pjisip-android-build on x86 when i build openssl with option -no-asm

i fiex 
Permission:
![default](https://user-images.githubusercontent.com/34454535/35477286-ffb3d894-03bf-11e8-9f60-55b79e1fc784.PNG)

Error debug on Android Studio:

`E/AudioRecord: Could not get audio input for session 89, record source 7, sample rate 8000, format 0x1, channel mask 0x10, flags 0
E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
D/PjSipLogWriter: 23:08:09.049 android_jni_de  ...Failure in initializing audio record.
D/PjSipLogWriter: 23:08:09.049 android_jni_de  ...Trying the default audio source.
E/AudioRecord: Could not get audio input for session 105, record source 0, sample rate 8000, format 0x1, channel mask 0x10, flags 0
E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
D/PjSipLogWriter: 23:08:09.058 android_jni_de  ...Failure in initializing audio record.
D/PjSipLogWriter: 23:08:09.058 android_jni_de  ...Destroying Android JNI stream...
A/art: art/runtime/java_vm_ext.cc:470] JNI DETECTED ERROR IN APPLICATION: expected reference of kind global reference but found local reference: 0x100009
A/art: art/runtime/java_vm_ext.cc:470]     in call to DeleteGlobalRef
A/art: art/runtime/java_vm_ext.cc:470]     from void org.pjsip.pjsua2.pjsua2JNI.Call_makeCall(long, org.pjsip.pjsua2.Call, java.lang.String, long, org.pjsip.pjsua2.CallOpParam)`

is very very big log:

`A/art: art/runtime/runtime.cc:427]   native: #44 pc 0067c60e  /system/lib/libart.so (MterpInvokeStatic+414)
A/art: art/runtime/runtime.cc:427]   native: #45 pc 000fb6a1  /system/lib/libart.so (artMterpAsmInstructionStart+14497)
A/art: art/runtime/runtime.cc:427]   native: #46 pc 002e5e98  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+488)
A/art: art/runtime/runtime.cc:427]   native: #47 pc 002ed5f0  /system/lib/libart.so (_ZN3art11interpreter30EnterInterpreterFromEntryPointEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameE+176)
A/art: art/runtime/runtime.cc:427]   native: #48 pc 0066cf79  /system/lib/libart.so (artQuickToInterpreterBridge+1049)
A/art: art/runtime/runtime.cc:427]   native: #49 pc 0010f39d  /system/lib/libart.so (art_quick_to_interpreter_bridge+77)
A/art: art/runtime/runtime.cc:427]   native: #50 pc 00091c42  /system/framework/x86/boot-framework.oat (???)
A/art: art/runtime/runtime.cc:427]   at org.pjsip.pjsua2.pjsua2JNI.Call_makeCall(Native method)
A/art: art/runtime/runtime.cc:427]   at org.pjsip.pjsua2.Call.makeCall(Call.java:107)
A/art: art/runtime/runtime.cc:427]   at com.carusto.ReactNativePjSip.PjSipService.handleCallMake(PjSipService.java:651)
A/art: art/runtime/runtime.cc:427]   at com.carusto.ReactNativePjSip.PjSipService.handle(PjSipService.java:342)
A/art: art/runtime/runtime.cc:427]   at com.carusto.ReactNativePjSip.PjSipService.access$200(PjSipService.java:56)
A/art: art/runtime/runtime.cc:427]   at com.carusto.ReactNativePjSip.PjSipService$3.run(PjSipService.java:241)
A/art: art/runtime/runtime.cc:427]   at android.os.Handler.handleCallback(Handler.java:751)
A/art: art/runtime/runtime.cc:427]   at android.os.Handler.dispatchMessage(Handler.java:95)
A/art: art/runtime/runtime.cc:427]   at android.os.Looper.loop(Looper.java:154)
A/art: art/runtime/runtime.cc:427]   at android.os.HandlerThread.run(HandlerThread.java:61)
A/art: art/runtime/runtime.cc:427] 
A/art: art/runtime/runtime.cc:427] 

       --------- beginning of crash
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 3569 (PjSipService)

        [ 01-27 23:08:09.252  1244: 1244 W/         ]
        debuggerd: handling request: pid=3541 uid=10076 gid=10076 tid=3569`

config_site.h:
`#define PJ_CONFIG_ANDROID 1
#include <pj/config_site_sample.h>`

can you tell me what is problem in AudioRecord?

Thank you!

**Comment by aenonGit** [comment]
have you tried to checkout latest dev? If no further activity I'll close this
